# Docker compose expects environment variables to come from a secrets.env file. Meaning that to initialize the
# container users must invoke -> docker compose --env-file secrets.env up backend.
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - default
      - price_tracker_net

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  db-developer:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    volumes:
      - postgres_dev_data:/var/lib/postgresql

volumes:
  postgres_data:
  postgres_dev_data: