# Core application properties
spring.config.activate.on-profile=developer
spring.application.name=hardware_price_tracker
server.port=8080

# Hibernate DDL set to read-only as Liquibase will now manage the schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
logging.level.org.springframework.jdbc.core.JdbcTemplate=TRACE

# Liquibase properties
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}